### ISSUE TITLE
Class translator does not exist

### ISSUE THREAD

**Issue by bpsi-staim** [AccessManager/access-manager#17]
`[2018-10-02 06:04:38] local.ERROR: Class translator does not exist {"exception":"[object] (ReflectionException(code: -1): Class translator does not exist at /home/test/access-manager/vendor/laravel/framework/src/Illuminate/Container/Container.php:752)
[stacktrace]
#0 /home/test/access-manager/vendor/laravel/framework/src/Illuminate/Container/Container.php(752): ReflectionClass->__construct('translator')
#1 /home/test/access-manager/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\\Container\\Container->build('translator')
#2 /home/test/access-manager/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\\Container\\Container->resolve('translator', Array)
#3 /home/test/access-manager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\\Container\\Container->make('translator', Array)
#4 /home/test/access-manager/vendor/laravel/framework/src/Illuminate/Container/Container.php(1195): Illuminate\\Foundation\\Application->make('translator')
#5 /home/test/access-manager/vendor/nesbot/carbon/src/Carbon/Laravel/ServiceProvider.php(27): Illuminate\\Container\\Container->offsetGet('translator')
#6 /home/test/access-manager/vendor/nesbot/carbon/src/Carbon/Laravel/ServiceProvider.php(21): Carbon\\Laravel\\ServiceProvider->updateLocale()
#7 [internal function]: Carbon\\Laravel\\ServiceProvider->boot()
#8 /home/test/access-manager/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#9 /home/test/access-manager/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /home/test/access-manager/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(AccessManager\\Base\\Extended\\Application), Array, Object(Closure))
#11 /home/test/access-manager/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(AccessManager\\Base\\Extended\\Application), Array, Array, NULL)
#12 /home/test/access-manager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(792): Illuminate\\Container\\Container->call(Array)
#13 /home/test/access-manager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\\Foundation\\Application->bootProvider(Object(Carbon\\Laravel\\ServiceProvider))
#14 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Carbon\\Laravel\\ServiceProvider), 3)
#15 /home/test/access-manager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): array_walk(Array, Object(Closure))
#16 /home/test/access-manager/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#17 /home/test/access-manager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(AccessManager\\Base\\Extended\\Application))
#18 /home/test/access-manager/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(296): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#19 /home/test/access-manager/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#20 /home/test/access-manager/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 {main}
"} 
`

**Comment by SirPrikol** [comment]
In last relise a have too this error

**Comment by benoit7866** [comment]
Is there any way to fix/go beyond this error ?

**Comment by Moowalker** [comment]
Run `composer update` from inside the created project directory (access-manager)
